--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/NurAzliYT/MultiVersion-Pmmp
build-by-default: true
branches:
- master
projects:
  MultiVersion-Pmmp:
    path: ""
    icon: "resources/icon.png"
...
